export enum FItemName {
  Period = "period",
  AccommodationType = "accommodationType",
  AccommodationCategory = "accommodationCategory",
  NextToSea = "nextToSea",
  GuestPicker = "guestPicker",
  Pet = "pet",
  BoatRope = "boatRope",
  BabyEquipment = "babyEquipment",
  FirstName = "firstName",
  LastName = "lastName",
  Email = "email",
  Birthday = "birthday",
  Country = "country",
  PhoneNumber = "phoneNumber",
  Note = "note",
}
